config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                user_blogs GET    /user_blogs(.:format)                                                                    user_blogs#index
#                           POST   /user_blogs(.:format)                                                                    user_blogs#create
#             new_user_blog GET    /user_blogs/new(.:format)                                                                user_blogs#new
#            edit_user_blog GET    /user_blogs/:id/edit(.:format)                                                           user_blogs#edit
#                 user_blog GET    /user_blogs/:id(.:format)                                                                user_blogs#show
#                           PATCH  /user_blogs/:id(.:format)                                                                user_blogs#update
#                           PUT    /user_blogs/:id(.:format)                                                                user_blogs#update
#                           DELETE /user_blogs/:id(.:format)                                                                user_blogs#destroy
#                           GET    /user_blogs/:blog_id/new_post(.:format)                                                  user_blogs#new_post
#                           POST   /user_blogs/:blog_id/create_post(.:format)                                               user_blogs#create_post
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :user_blogs

  get "/user_blogs/:blog_id/new_post", to: "user_blogs#new_post"
  post "/user_blogs/:blog_id/create_post", to: "user_blogs#create_post"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
# == Schema Information
#
# Table name: blog_posts
#
#  id           :bigint           not null, primary key
#  content      :text
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_blog_id :bigint
#
# Indexes
#
#  blog_post_id_index                (id) UNIQUE
#  blog_posts_user_blog_id_index     (user_blog_id)
#  index_blog_posts_on_content       (content)
#  index_blog_posts_on_created_at    (created_at)
#  index_blog_posts_on_title         (title)
#  index_blog_posts_on_updated_at    (updated_at)
#  index_blog_posts_on_user_blog_id  (user_blog_id)
#
class BlogPost < ApplicationRecord
  belongs_to :user_blog

  scope :for_blog, ->(id) { where("user_blog_id = ?", id) }

  before_validation :check_title_presence

  private

    def check_title_presence
      if title == "" || title == nil
        errors.add(:title, "can not be blank")
      end
    end
end

app/models/user_blog.rb
# == Schema Information
#
# Table name: user_blogs
#
#  id         :bigint           not null, primary key
#  title      :string
#  author     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class UserBlog < ApplicationRecord
  validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_blogs_controller.rb
class UserBlogsController < ApplicationController
  before_action :set_user_blog, only: [:show, :edit, :update, :destroy]

  # GET /user_blogs
  # GET /user_blogs.json
  def index
    @user_blogs = UserBlog.all
  end

  # GET /user_blogs/1
  # GET /user_blogs/1.json
  def show
  end

  # GET /user_blogs/new
  def new
    @user_blog = UserBlog.new
  end

  # GET /user_blogs/1/edit
  def edit
  end

  # POST /user_blogs
  # POST /user_blogs.json
  def create
    @user_blog = UserBlog.new(user_blog_params)

    result  = @user_blog.save! rescue false
    respond_to do |format|
      if result
        format.html { redirect_to @user_blog, notice: 'User blog was successfully created.' }
        format.json { render :show, status: :created, location: @user_blog }
      else
        format.html { render :new }
        format.json { render json: @user_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_blogs/1
  # PATCH/PUT /user_blogs/1.json
  def update
    respond_to do |format|
      if @user_blog.update(user_blog_params)
        format.html { redirect_to @user_blog, notice: 'User blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_blog }
      else
        format.html { render :edit }
        format.json { render json: @user_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_blogs/1
  # DELETE /user_blogs/1.json
  def destroy
    @user_blog.destroy
    respond_to do |format|
      format.html { redirect_to user_blogs_url, notice: 'User blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_post
    @blog = UserBlog.find(params[:blog_id])
    @blog_post = BlogPost.new(user_blog: @blog)
  end

  def create_post
    @blog = UserBlog.find_by(id: params[:blog_id])
    @blog_post = BlogPost.new(
      user_blog_id: @blog.id,
      title: params[:blog_post][:title],
      content: params[:blog_post][:content]
    )

    if @blog_post.save
      redirect_to action: :index
    else
      render :new_post
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_blog
      @user_blog = UserBlog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_blog_params
      params.require(:user_blog).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_blogs_helper.rb
module UserBlogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_blogs/_form.html.erb
<%= form_for @user_blog, :html => { :class => "form-horizontal user_blog" } do |f| %>

  <% if @user_blog.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user_blog.errors.count, "error") %> prohibited this user_blog from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user_blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :author, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :author, :class => 'form-control' %>
    </div>
    <%=f.error_span(:author) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_blogs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/user_blogs/edit.html.erb
<%- model_class = UserBlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_blogs/index.html.erb
<%- model_class = UserBlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th> Posts count </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @user_blogs.each do |user_blog| %>
      <tr>
        <td><%= link_to user_blog.id, user_blog_path(user_blog) %></td>
        <td><%= user_blog.title %></td>
        <td><%= user_blog.author %></td>
        <td><%=l user_blog.created_at %></td>
        <td><%= BlogPost.for_blog(user_blog.id).to_a.size %></td>
        <td>
          <%= link_to 'New Post', "/user_blogs/#{user_blog.id}/new_post", :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_blog_path(user_blog), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_blog_path(user_blog),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_blog_path,
            :class => 'btn btn-primary' %>

app/views/user_blogs/new.html.erb
<%- model_class = UserBlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_blogs/new_post.html.erb
<%- model_class = UserBlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for @blog_post, url: "/user_blogs/#{@blog_post.user_blog.id}/create_post", :html => { :class => "form-horizontal blog_post" } do |f| %>

  <% if @blog_post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @blog_post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :content, :class => 'form-control' %>
    </div>
    <%=f.error_span(:content) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/user_blogs/show.html.erb
<%- model_class = UserBlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @user_blog.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
  <dd><%= @user_blog.author %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              user_blogs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_blog_path(@user_blog), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_blog_path(@user_blog),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>